services:
  db: 
    image: postgres:15.6
    restart: always
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
    env_file:
      - ./back/.env
    ports:
      - 5432:5432

  app:
    restart: always
    build: 
      context: ./back
      dockerfile: laravel.dockerfile
    volumes:
      - ./back:/app
    depends_on:
      - db
    ports:
      - 8000:8000
      
  web:
    restart: always
    build:
      context: ./front
      dockerfile: vue.dockerfile
    ports:
      - 80:80
    volumes:
      - ./front:/app
    depends_on:
      - app

volumes:
  dbdata: